config/routes.rb
Rails.application.routes.draw do
  get 'results_shops/index'

  get 'search_shops/index'

  get 'welcome/index'

  resources :shops

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
    include Filterable

    scope :city, -> (city) { where city: city }

    geocoded_by :full_address # full_address is a method which take some model's attributes to get a formatted address for example

    # the callback to set longitude and latitude
    after_validation :geocode

    def full_address
        "#{address}, #{zip}, #{city}, #{country_code}"
    end

    def gmaps4rails_address
        "#{address}, #{zip}, #{city}, #{country_code}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/results_shops_controller.rb
class ResultsShopsController < ApplicationController
    def index
        if params[:location].present?
            @critere = "recherche par lieu"
            @location = params[:location]
            @nombre = (params[:nombre].present? ? params[:nombre] : 5)
            @distance = (params[:distance].present? ? params[:distance] : 10)

            # @shops = Shop.near(params[:location], params[:distance] || 10, order: :distance)
            @shops = Shop.near(@location, @distance, :units => :km).limit(@nombre)
            # @shops = Shop.near("rue Winston Churchill", 10, :units => :km).limit(5)

        elsif params[:latitude].present? && params[:longitude].present?
            @nombre = (params[:nombre].present? ? params[:nombre] : 5)
            @critere = "recherche par coordonnées"
            arr = [params[:latitude], params[:longitude]]
            @shops = Shop.near(arr, 1000).limit(@nombre)
        else
            @critere = "pas de critère"
            @shops = Shop.all
        end
        @trouve = @shops.length != 0
        @hash = Gmaps4rails.build_markers(@shops) do |shop, marker|
            marker.lat shop.latitude
            marker.lng shop.longitude
            marker.title shop.name
            marker.infowindow shop.name
        end
    end
end

app/controllers/search_shops_controller.rb
class SearchShopsController < ApplicationController
    def index


    end


end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    def index
        @shops = Shop.filter(params.slice(:city))

        # @shops = Shop.all
    end

    # def import
    #     Shop.import(params[:file])
    #     redirect_to root_url
    # end

    def show
        @shop = Shop.find(params[:id])
    end

    def new
        @shop = Shop.new
    end

    def edit
        @shop = Shop.find(params[:id])
    end

    def update
        @shop = Shop.find(params[:id])

        if @shop.update(shop_params)
            redirect_to @shop
        else
            render 'edit'
        end
    end

    def create
        @shop = Shop.new(shop_params)

        if @shop.save
            redirect_to @shop
        else
            render 'new'
        end
    end


    def destroy
        @shop = Shop.find(params[:id])
        @shop.destroy

        redirect_to shops_path
    end

    private
    def shop_params
        params.require(:shop).permit(:chain, :name, :latitude, :longitude, :address, :city, :zip, :phone, :country_code)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_shops_helper.rb
module ResultsShopsHelper
end

app/helpers/search_shops_helper.rb
module SearchShopsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magasins</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//maps.google.com/maps/api/js?v=3.35&libraries=geometry&key=AIzaSyAvWjW7A7-OFiJ40BVvWx3jZd0hsCsZtwI" type="text/javascript"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/results_shops/index.html.erb
<div class="container text-center">
    <h1>Résultats de la recherche : <%= @critere %></h1>
    <%= link_to search_shops_index_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-search"></span> Autre recherche
    <% end %><br>
    <h3>Paramètres</h3>
    <% if defined?(@location) %> Lieu : <%= @location %><br> <%end%>
    <% if defined?(@distance) %>Distance : <%= @distance %> km<br><%end%>
    <% if (!params[:latitude].to_s.empty?) %>Latitude: <%= params[:latitude] %><br><%end%>
    <% if (!params[:longitude].to_s.empty?) %>Longitude : <%= params[:longitude] %><br><%end%>
    <% if defined?(@nombre) %>Nombre max résultats : <%= @nombre %><br><%end%>

    <h3>Résultats</h3>
    <div id="resultats" class="container">
        <ul class="nav nav-tabs nav-justified">
            <li class="active">
                <a href="#1a" data-toggle="tab">Carte</a>
            </li>
            <li>
                <a href="#2a" data-toggle="tab">Liste</a>
            </li>
        </ul>

        <div class="tab-content clearfix">
            <div class="tab-pane active" id="1a" style="border:solid 1px grey;">
                <div style='width: 800px; display:inline-block;'>
                    <div id="map" style='width: 800px; height: 400px;'></div>
                </div>
            </div>
            <div class="tab-pane" id="2a" style="border:solid 1px grey;">
                <% if @shops.length != 0 %>
                <table class="table table-striped">
                    <tr>
                        <th>Chaîne</th>
                        <th>Nom</th>
                        <th>Latitude</th>
                        <th>Longitude</th>
                        <th>Adresse</th>
                        <th>Ville</th>
                        <th>Code postal</th>
                        <th>Téléphone</th>
                        <th>Code pays</th>
                    </tr>

                    <% @shops.each do |shop| %>
                    <tr>
                        <td><%= shop.chain %></td>
                        <td><%= shop.name %></td>
                        <td><%= shop.latitude %></td>
                        <td><%= shop.longitude %></td>
                        <td><%= shop.address %></td>
                        <td><%= shop.city %></td>
                        <td><%= shop.zip %></td>
                        <td><%= shop.phone %></td>
                        <td><%= shop.country_code %></td>
                    </tr>
                    <% end %>
                </table>
                <% else %>
                <div> Aucun résultat trouvé </div>
                <% end %>
            </div>
        </div>
    </div>

</div>
<script type="text/javascript">
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    var markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();

});
</script>

app/views/search_shops/index.html.erb
<div class="jumbotron">
    <div class="container text-center">
        <h1>Formulaire de recherche</h1>

        <h2>Recherche par coordonnées</h2>
        <button class="btn btn-success" onclick="getLocation()"><span class="glyphicon glyphicon-screenshot"></span> Localisez moi</button>
        <%= form_tag results_shops_index_path, method: :get do %>
        <div class="form-group">
            <div class="col-xs-6" style="text-align:right;">
                <%= label :latitude, "Latitude : " %>
            </div>
            <div class="col-xs-6">
                <%= number_field_tag :latitude, params[:latitude], id: "latitude", :step => "any", :class=>"form-control"  %><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-6" style="text-align:right;">
                <%= label :longitude, "Longitude : " %>
            </div>
            <div class="col-xs-6">
                <%= number_field_tag :longitude, params[:longitude], id: "longitude", :step => "any", :class=>"form-control"  %><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-6" style="text-align:right;">
                <%= label :nombre, "Nombre de résultats : " %>
            </div>
            <div class="col-xs-6">
                <%= number_field_tag :nombre, params[:nombre], placeholder: "5 par défaut", :class=>"form-control"  %><br>
            </div>
        </div>

        <%= submit_tag "Rechercher", :class => 'btn btn-primary' %>
        <% end %>
        <h2>Recherche par lieu</h2>
        <%= form_tag results_shops_index_path, method: :get do %>
        <div class="form-group">
            <div class="col-xs-6" style="text-align:right;">
                <%= label :location, "Recherchez des magasins près de : " %>
            </div>
            <div class="col-xs-6">
                <%= text_field_tag :location, params[:location], id: "location", placeholder: "Ville, adresse...", :class=>"form-control"  %><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-6" style="text-align:right;">
                <%= label :distance, "Dans un rayon de : " %>
            </div>
            <div class="col-xs-6">
                <%= number_field_tag :distance, params[:distance], placeholder: "10 km par défaut", :class=>"form-control"  %><br>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-6" style="text-align:right;">
                <%= label :nombre, "Nombre de résultats : " %>
            </div>
            <div class="col-xs-6">
                <%= number_field_tag :nombre, params[:nombre], placeholder: "5 par défaut", :class=>"form-control"  %><br>
            </div>
        </div>

        <%= submit_tag "Rechercher", :class => 'btn btn-primary' %>
        <% end %>


    </div>
</div>

app/views/shops/_form.html.erb
<div class="row">
    <%= form_with model: @shop, local: true do |form| %>
    <% if @shop.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@shop.errors.count, "error") %> prohibited
            this shop from being saved:
        </h2>
        <ul>
            <% @shop.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :chain, 'Chaîne'%>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :chain, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :name, 'Nom' %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :name, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :latitude %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :latitude, step: :any, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :longitude %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :latitude, step: :any, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :address, "Adresse" %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :address, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :city, "Ville" %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :city, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :zip, "Code postal" %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :zip, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :phone, "Téléphone" %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :phone, :class=>"form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-xs-6" style="text-align:right;">
            <%= form.label :country_code, "Code pays" %>
        </div>
        <div class="col-xs-6">
            <%= form.text_field :country_code, :class=>"form-control" %>
        </div>
    </div>
</div>

<div style="margin-top:10px;">

    <%= form.submit 'Créer un magasin', :class => "btn btn-success" %>
    <%= link_to 'Retour', shops_url, :class => 'btn btn-primary' %>

</div>
<% end %>

app/views/shops/edit.html.erb
<div class="container text-center">

<h1>Modifier un magasin</h1>

<%= render 'form' %>

</div>

app/views/shops/index.html.erb
<div class="container-fluid">
<%= flash[:notice] %>
<h1 style="display:inline-block;">Tous les magasins</h1>
<%= link_to new_shop_path, :class => 'btn btn-success', :style => "display:inline-block;margin:10px;" do %>
    <span class="glyphicon glyphicon-plus"></span> Nouveau
<% end %>
<%= link_to 'Retour', root_url, :class => 'btn btn-primary' %>

<table class="table table-striped">
    <tr>
        <th>Chaîne</th>
        <th>Nom</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Adresse</th>
        <th>Ville</th>
        <th>Code postal</th>
        <th>Téléphone</th>
        <th>Code pays</th>
        <th>Actions</th>
    </tr>

    <% @shops.each do |shop| %>
    <tr>
        <td><%= shop.chain %></td>
        <td><%= shop.name %></td>
        <td><%= shop.latitude %></td>
        <td><%= shop.longitude %></td>
        <td><%= shop.address %></td>
        <td><%= shop.city %></td>
        <td><%= shop.zip %></td>
        <td><%= shop.phone %></td>
        <td><%= shop.country_code %></td>
        <td class="text-nowrap">

            <%= link_to shop_path(shop), :class => 'btn btn-primary' do %>
                <span class="glyphicon glyphicon-search"></span>
            <% end %>

            <%= link_to edit_shop_path(shop), :class => 'btn btn-warning' do %>
                <span class="glyphicon glyphicon-pencil"></span>
            <% end %>

            <%= link_to shop_path(shop), :class => 'btn btn-danger', method: :delete, data: { confirm: 'Êtes vous sûr?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
            <% end %>
        </td>
    </tr>
    <% end %>
</table>

</div>

app/views/shops/new.html.erb
<div class="container text-center">

<h1>Ajout d'un magasin</h1>

<%= render 'form' %>

</div>

app/views/shops/show.html.erb
<div class="container text-center">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><%= @shop.name %></h3>
        </div>
        <div class="panel-body">
            Chaîne: <%= @shop.chain %><br>
            Latitude: <%= @shop.latitude %><br>
            Longitude: <%= @shop.longitude %><br>
            Adresse: <%= @shop.address %><br>
            Ville: <%= @shop.city %><br>
            Code postal: <%= @shop.zip %><br>
            Téléphone: <%= @shop.phone %><br>
            Code pays: <%= @shop.country_code %>
        </div>
    </div>

    <%= link_to 'Retour', root_url, :class => 'btn btn-primary' %>
    <%= link_to edit_shop_path(@shop), :class => 'btn btn-warning' do %>
    <span class="glyphicon glyphicon-pencil"></span> Modifier
    <% end %>

</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <div class="container text-center">
        <h1>Bienvenue sur Thomium</h1>
        <p>Vous pouvez gérer des magasins et chercher ceux près de vous</p>
        <%= link_to shops_path, :class => 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-list"></span> Gestion
        <% end %>
        <%= link_to search_shops_index_path, :class => 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-search"></span> Rechercher
        <% end %>
    </div>
</div>